apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx1
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: nginx:latest
        ports:
        - containerPort: 80
