apiVersion: v1
kind: Service
metadata:
  name: nginx1
  namespace: test
spec:
  type: LoadBalancer
  #loadBalancerIP: <loadBalancerIP>      # for set static ip
  selector:
    app: nginx1
  ports:
  - port: 80
    name: http
