apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rancherv2
  namespace: hello-rancherv2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-rancherv2
  template:
    metadata:
      labels:
        app: hello-rancherv2
    spec:
      containers:
        - name: hello-rancher
          image: peteindockerhub/hello-rancher:1.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          env:
            - name: CONTAINER_COLOR
              value: teal
            - name: TITLE
              value: Hello Rancher              
            - name: PETS
              value: whitecows   
          readinessProbe:
            httpGet:
              port: web
              path: /
